import {StyleSheet, Dimensions} from 'react-native';
const {height, width} = Dimensions.get('window');
import Colors from '../../Constraints/Colors';

const styles = StyleSheet.create({
  container: {
    backgroundColor: Colors.PRIMARY_WHITE,
    flex: 1,
  },
  inputContainerPaas: {
    marginTop: '4%',
    paddingHorizontal: '5%',
    width: '90%',
    height: 50,
    marginTop: '3%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    alignSelf: 'center',
    borderRadius: 10,
    borderColor: Colors.GREY,
    borderStartWidth: 1,
    borderRightWidth: 1,
    borderTopWidth: 1,
  },
  inputStyle: {
    backgroundColor: Colors.PRIMARY_WHITE,
    width: '90%',
    fontSize: 16,
    fontWeight: '400',
    lineHeight: 24,
    fontFamily: Fonts.FIGTREE,
  },
  btnsContainer: {
    width: '90%',
    alignSelf: 'center',
    marginTop: '6%',
    flexDirection: 'row',
    alignItems: 'center',
  },
  phoneInputContainer: {
    width: '72%',
    justifyContent: 'center',
    borderWidth: 1,
    alignSelf: 'center',
    borderRadius: 10,
    borderColor: Colors.GREY,
  },
  phoneInput: {
    backgroundColor: Colors.PRIMARY_WHITE,
    width: '90%',
    fontSize: 16,
    fontWeight: '400',
    lineHeight: 24,
    fontFamily: Fonts.FIGTREE,
    marginLeft: '4%',
  },
  errTxt: {
    width: '88%',
    color: 'red',
    fontSize: 12,
    alignSelf: 'center',
    marginTop: '2%',
    marginBottom: 5,
    fontFamily: Fonts.FIGTREE,
  },
  inputStyle: {
    backgroundColor: Colors.PRIMARY_WHITE,
    width: '90%',
    fontSize: 16,
    fontWeight: '400',
    lineHeight: 24,
    fontFamily: Fonts.FIGTREE,
  },
  inputContainer: {
    width: '90%',
    marginTop: '3%',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    alignSelf: 'center',
    borderRadius: 10,
    borderColor: Colors.GREY,
  },
  headerStyl: {
    color: Colors.BLACK,
    fontSize: 22,
    fontWeight: '600',
    lineHeight: 26,
    fontStyle: 'normal',
    width: '90%',
    fontFamily: Fonts.FIGTREE,
    marginTop: '8%',
    alignSelf: 'center',
  },
  dashView: {
    borderStyle: 'dashed',
    borderColor: Colors.GREY,
    borderWidth: 1.5,
    borderRadius: 20,
    width: '90%',
    alignSelf: 'center',
    height: 155,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: '5%',
  },
  imgCam: {
    width: 66,
    height: 66,
    borderRadius: 66 / 2,
    backgroundColor: '#F2F2F2',
    alignItems: 'center',
    justifyContent: 'center',
  },
  imgVehicleStyle: {
    borderRadius: 20,
    width: '90%',
    alignSelf: 'center',
    height: 150,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: '5%',
  },
});
export default styles;
