export default Constraints = {
  DONT_HAVE_ACCOUNT: 'You don’t have an Account? ',
  SIGN_UP: 'Sign Up',
  LOGIN: 'Login',
  OR: 'or',
  EMAIL_PHONE_NUMBER: 'Email',
  AREA: 'Area',
  PASSWORD: 'Pin',
  ENTER_YOUR_PASS: 'Enter Your Pin',
  FORGOT_PASSWORD: 'Forgot Pin',
  TERMS_COND: 'I agree with the terms and agreements.',
  USER_NAME: 'Your Name',
  CONTACT_NUNM: 'Contact Number',
  CLINIC_NAME: 'Clinic Name',
  GENDER: 'Gender',
  POST_TO_ADMIN: 'Broadcast',
  GALLERY: 'Gallery',
  CAMERA: 'Camera',
  UPDATE: 'Update',
  EDIT: 'Edit',
  VEHICLE_REG_NUM: 'Vehicle Registration Number',
  DATE_OF_BIRTH: 'Date Of Birth',
  PHONE_IMEI: 'Phone IMIE Number (optional)',
  GSM_NETWORK: 'GSM Network',
  ADDRESS: 'Address',
  USER_CATEGORIES: 'User Categories',
  CREATE_PASSWORD: 'Create Pin',
  CONFIRM_PASSWORD: 'Confirm Pin',
  MALE: 'Male',
  FEMALE: 'Female',
  MTN: 'MTN',
  AIRTEL: 'Airtel',
  _9MOBILE: '9Mobile',
  GLO: 'Glo',
  CHOOSE_SERVICE: 'Choose Service',
  Well_Being_check: 'Well being Check Services',
  Well_Being_check2: 'Wellbeing Check',
  WELLBEING_DETAIL:
    'Stay connected and in control of your safety with our virtual wellbeing check services!',
  TOWING_SERVICE: 'Towing Service',
  TOWING_DETAIL:
    'Click and Connect to the nearest towing service close to you.',
  AMBULANCE_SERVICE: 'Ambulance',
  AMBULANCE_DETAIL: 'Click and  connect to the nearest Ambulance close to you',
  FIRE_SERVICE: 'Fire Services',
  FIRE_DETAIL: 'Click and Connect to the fire office',
  ROAD_SAFETY: 'Road Safety',
  RdSafety_Detail: 'Alert Nigeria Police from our app',
  WHISTLEBLOWER: 'Whistleblower Services',
  WHISTLEBLOWER_SCREEN: 'Whistleblower',
  WHISTLEBLOWERDETAIL: 'Blow a Whistle to stop Crime and Earn',

  VERIFICATION: 'Verification',
  ENTER_CODE_TO_SEND: 'Enter the code sent to ',
  DIDNT_RECEIVE_SMS: 'Don’t receive an SMS? ',
  RESEND_SMS: 'Resend SMS',
  DONE: 'Done',
  PAY: 'Pay',
  CALCULATE: 'Calculate',
  CHOOSE_THIS_SERVICE: 'Choose this service',
  VERIFIED: 'Verified',
  OTP_VERIFIED: 'Your OTP is verified.',
  SELECT_SUBSRICPTION: 'Select Subscription',
  LOREM: 'Lorem ipsum dolor sit amet, consectetuer \nadipiscing elit, sed.',
  SUBTITLE_SUBSCRIPTION:
    'choose one of the mentioned plan to proceed further in this app.',
  FREE_MEMBERSHIP: 'Free Membership',
  FEATURES: 'Features',
  FREE: 'Free',
  SEND_SOS_TO_EMERGENCY: 'Send SOS Message to Emergency Contact',
  SEND_LOCATION: 'Share Location',
  BASIC_MEMBERSHIP: 'Basic Membership',
  YEARLY: 'Yearly',
  PREMIUM_MEMBERSHIP: 'Gold Membership',
  PAID: 'Paid',
  REGISTER_JOUNEY: 'Register a Journey',
  REGISTER_WELLBEING_CHECK: 'Request for wellbeing Check',
  CONTCT_NEAREST_TOWING_VEHICLE: 'Contact Nearest Towing Vehicle',
  OTHER: 'Others...',
  ROAD_SAFETY: 'Police Alert',
  TOWING_SERVICE: 'Towing Services',
  FIRE_SERVICE: 'Fire Service',
  AMBULANCE_SERVICE: 'Ambulance Services',
  BACK_TO_HOME: 'Back to Home',
  WELLBEING_CHECK: 'Wellbeing Check Services',
  VIRTUAL_TRAVEL_GUARD: 'Virtual Travel Guard',
  VIRTUAL_HOME_CHECK: 'Virtual Home Check',
  VTG: 'Start your trip under protection of our company to travel safe',
  VHC: 'Start your virtual home check to stay updated by our company',
  REGISTER_YOUR_JOUNEY: 'Please Register your Journey Below',
  USE_MY_CURRENT_LOCATION: 'Use my Current location',
  WELL_BEING_CHECK_INTERVAL: 'Set Wellbeing Check Interval',
  FAMILY_MEMBER: 'Family Member',
  BUNINESS: 'Business Partner',
  PARTNER_CLIENT: 'Customer',
  FRIEND: 'Friend',
  NAME: 'Name',
  ALONE: 'Alone',
  MOBILE_NUMBER: 'Mobile Number',
  ARRIVAL_DATE: 'Arrival Date',
  ARRIVAL_TIME: 'Arrival Time',
  MODE_OF_TRANSPORT: 'Mode of Transport',
  OWN_TRANSPORT: 'Own Transport',
  PUBLIC_TRANSPORT: 'Public Transport',
  TRAIN: 'Train',
  CAM: 'Camera',
  VEHICLE_NUMBER: 'Vehicle Number',
  VEHICLE_NAME: 'Vehicle Name',
  VEHICLE_MAKER: 'Vehicle Maker',
  VEHICLE_MODEL: 'Vehicle Model',
  START_TRIP: 'Start Trip',
  ENTER_TRANSPORT_COMPANY: 'Enter Transport Company',
  TYPE_TRANSPORT: 'Type of Transport Vehicle',
  VEHICLE_REG: 'Vehicle Registration',
  TIME_OF_DEPART: 'Time of Departure',
  DEPART_STATION: 'Departure Station',
  ARRIVAL_STATION: 'Arrival Station',
  LIVE_TRACKING_ON: 'Live Tracking ON',
  STOP_VEH_IN_WHICH_TRANVE: `Stop vehicle in which you're`,
  BUS: 'Bus',
  CAR: 'Car',
  START_DATE: 'Start Date',
  END_DATE: 'End Date',
  TRAVEL_PARTER_RELASHIONSHIP: 'Traveling Partner Relationship',
  REG_WHERE_YOU_NEED: 'Register where you need Virtual Check',
  SET_WELLEING_CHECK_INTERVAL: 'Set Wellbeing check interval',
  UPDATE_SOSO_SETTING: 'Update SOS Signal',
  SELECT_HERE: 'Select here',
  TAKE_SELFIE: 'Take Selfie',
  TAKE_PHOTO_IDENTIFICATION: 'Take your photo for Identification',
  UPLOAD_VEHICLE_PHOTO: 'Upload your Vehicle photo for Identification',
  UPLOAD_VEHICLE: 'Upload Vehicle',
  UPLOAD_IMAGE: 'Upload Image',
  SOS_ALERT: 'SOS Alert Setting Daily',
  STOP_TRIP: 'Stop Trip',
  RESUME_TRIP: 'Resume Trip',
  END_TRIP: 'End Trip',
  NOTE: 'Note:',
  NOTE_SUB:
    'If you do not end the trip a rescue team will be dispatch to your location',
  POPULAR_SERVICES: 'Popular Services',
  BIOMETRIC: 'Biometric Login',
  ENTER_PIN: 'Enter PIN',
  HOTEL: 'Hotel',
  HOME: 'Home',
  FRIENDS: 'Friends House',
  PARTY: 'Party',
  BRIRIAL_CERMNOY: 'Burial Ceremony',
  LOADING: 'Please wait...',
  CANCEL: 'Cancel',
  EMAIL: 'Email',
  NOTIFICATIONS: 'Notifications',
  PAYMENT: 'Payment Method',
  CUSTOMER_SUPPORT: 'Customer Support',
  WHATSAPP_CONTACT: 'Whatsapp Contact',
  PHONE_NUMBER: 'Phone Number',
  EMAIL: 'Email',
  MASTER: 'Master Card',
  MASTER_SUB: '************3425',
  VISA: 'Debit/Credit Card',
  VISA_SUB: '************3425',
  STRIPE: 'Payment Via Stripe',
  PAYSTACK: 'Payment Via Paystack',
  CONTINUE: 'Continue',
  BANK_TRANSFER: 'Bank Transfer',
  BANK_TRANSFER_SUB: 'Bank Transfer Takes Upto 2 Business Days',
  EMERGENCY_CONTACT: 'Emergency Contact',
  REGISTERED_VEHICLES: 'Registered Vehicles',
  ADD_EMERGENCY_CONTACT: 'Add Contact',
  ADD_VEHICLES: 'Add Vehicle',
  SAVE: 'Save',
  USER_MODE: 'User Mode',
  PROVER_MODE: 'Operator Mode',
  OPERATOR: 'Operator',
  OPERATOR_SUPPORT: 'Operator support',
  RELATION: 'Relation',
  SUBMIT: 'Submit',
  TIME: 'Time',
  DATE: 'Date',
  KIDNAP: 'Report kidnapping',
  SEARCH_A_HOUSE: 'Search a house',
  STOP_KILLING: 'Stop ritual killing',
  REPORT_CRIMINAL: 'Report a criminal in your area',
  OTHERR: 'Others',
  POST: 'Post',
  VEHICLE_PIC: 'Vehicle Pic',
  BACK_TO_HOME: 'Back to home',
  LAGOS: 'Lagos',
  IBANADAN: 'Ibadan',
  KAFANCHAN: 'Kafanchan',
  ENUGU: 'Enugu',
  WARI_ITAKI: 'Warri- Itakpe',
  ABUJA: 'Abuja',
  ZARIA: 'Zaria',
  BAUCHI: 'Bauchi',
  CAR_DETAILS: 'Vehicle details',
  PRICE: 'Hours *',
  OGAN: 'Ogun',
  KADUNA: 'Kaduna',
  NUM_HOURS: 'Enter Hours',
  SUBSCIPTION_TITLE: 'Purchase Well being Check',
  HOURLY_RATE: 'Hourly Rate:',
  RATING: 'Rating:',
  TOTAL_PRICE: 'Total Price',
  SUBSCRIBE_HOURLY: 'Subscribe hourly to get protected.',
  RATE_US: 'Rate Us',
  SUB_TITLE_SUBSCRPTION_WE_OFFER:
    'We offer hourly check services to connect people for  security assistance.',
  SUB_TITLE_SUBSCRPTION:
    "Our Wellbeing Check Services are essential for ensuring safety of life and assets in our community in collaboration with Security Agencies. We strive to connect individuals with immediate security help,seamlessly linking individual's to  these agencies in a timely manner.",
};
