import {StyleSheet, StatusBar, Dimensions} from 'react-native';
const {height, width} = Dimensions.get('window');
import Fonts from '../../Constraints/Fonts';
import Colors from '../../Constraints/Colors';
import {responsiveFontSize} from 'react-native-responsive-dimensions';

const styles = StyleSheet.create({
  container: {
    backgroundColor: Colors.PRIMARY_WHITE,
    flex: 1,
  },

  amountTxt: {
    color: Colors.BLACK,
    fontSize: 26,
    fontWeight: '700',
    lineHeight: 31,
    fontStyle: 'normal',
    fontFamily: Fonts.FIGTREE,
  },
  headerStyl: {
    color: Colors.BLACK,
    fontSize: 24,
    fontWeight: 'bold',
    lineHeight: 29,
    fontStyle: 'normal',
    fontFamily: Fonts.FIGTREE,
  },
  headerStyl2: {
    color: Colors.BLACK,
    fontSize: 14,
    fontWeight: '400',
    lineHeight: 17,

    fontFamily: Fonts.FIGTREE,
    marginTop: 10,
  },
  headerStyl3: {
    color: Colors.BLACK,
    fontSize: 14,
    fontWeight: '400',
    lineHeight: 17,
    fontStyle: 'normal',
    fontFamily: Fonts.FIGTREE,
    marginLeft: 8,
  },

  topContainer: {
    width: '90%',
    height: 80,
    marginTop: StatusBar.currentHeight + 20,
    marginBottom: '3%',
    alignSelf: 'center',
    justifyContent: 'space-evenly',
  },

  phoneInput: {
    backgroundColor: Colors.PRIMARY_WHITE,
    width: '70%',
    height: 40,
    fontSize: 16,
    fontWeight: '400',
    lineHeight: 24,
    fontFamily: Fonts.FIGTREE,
    marginLeft: '4%',
  },
  phoneInputContainer: {
    width: '72%',
    height: 50,
    justifyContent: 'center',
    borderWidth: 1,
    alignSelf: 'center',
    borderRadius: 10,
    borderColor: Colors.GREY,
  },
  forgotStyle: {
    width: '90%',
    marginTop: '3%',
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  imgContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    height: 240,
  },

  center: {
    height: 20,
    width: 20,
    borderRadius: 4,
  },

  boxStyle: {
    width: '90%',
    backgroundColor: Colors.PRIMARY_WHITE,
    borderRadius: 24,
    marginTop: '3%',
    marginBottom: '5%',
    alignSelf: 'center',
    flexDirection: 'column',
    borderWidth: 1,
    borderColor: Colors.GREY,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 10},
    shadowOpacity: 0.1,
    shadowRadius: 3.84,
    elevation: 4,
  },
  blackBox: {
    height: 71,
    width: '100%',
    borderTopStartRadius: 24,
    borderTopEndRadius: 24,
    backgroundColor: Colors.BLACK,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  icon: {
    width: 45,
    height: 45,
    borderRadius: 45 / 2,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.PRIMARY_WHITE,
  },
  membershipTxt: {
    marginLeft: 12,
    fontFamily: Fonts.FIGTREE,
    color: Colors.PRIMARY_WHITE,
    fontSize: responsiveFontSize(3),
    fontWeight: 'bold',
    lineHeight: 26,
  },
  CheckIconStyle: {
    width: 21,
    height: 21,
    borderRadius: 4,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    backgroundColor: Colors.BLACK,
  },
  innerBox: {
    width: '90%',
    flexDirection: 'row',
    marginTop: '4%',
  },
  amountBox: {
    borderTopWidth: 1,
    borderTopColor: '#EFEFF4',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    alignSelf: 'center',
    marginTop: '5%',
    paddingVertical: 15,
  },
  innerAmountBox: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '90%',
    alignSelf: 'center',
    marginTop: '2%',
  },
  subscriptionBox: {
    alignSelf: 'center',
    width: '90%',
    flexDirection: 'column',
    justifyContent: 'center',
    marginTop: '9%',
  },
  btnStyle: {
    height: 46,
    borderRadius: 8,
    width: '55%',
    backgroundColor: Colors.BLACK,
    borderColor: Colors.BLACK,
  },
  btnTxt: {
    color: Colors.BTN_TXT_WHITE,
    fontSize: 16,
    fontWeight: '500',
    fontStyle: 'normal',
    lineHeight: 19,
    fontFamily: Fonts.FIGTREE,
  },
  featureTxt: {
    color: Colors.BLACK,
    fontSize: 18,
    fontWeight: '500',
    fontStyle: 'normal',
    lineHeight: 31,
    fontFamily: Fonts.FIGTREE,
  },
  line: {height: 1, backgroundColor: 'black'},
});
export default styles;
