import {StyleSheet, Dimensions} from 'react-native';
const {height, width} = Dimensions.get('window');
import Colors from '../../Constraints/Colors';

const styles = StyleSheet.create({
  container: {
    backgroundColor: Colors.PRIMARY_WHITE,
    flex: 1,
  },
  btnsContainer: {
    width: '90%',
    alignSelf: 'center',
    marginTop: '6%',
    flexDirection: 'row',
    alignItems: 'center',
  },
  pickerStyle: {
    alignItems: 'center',
    justifyContent: 'center',
    width: '25%',
    height: 50,
    backgroundColor: Colors.PRIMARY_WHITE,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Colors.GREY,
    flexDirection: 'row',
  },
  phoneInputView: {
    marginTop: '3%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '90%',
    height: 50,
    alignSelf: 'center',
  },
  inputContainerPaas: {
    marginTop: '4%',
    paddingHorizontal: '5%',
    width: '90%',
    height: 50,
    marginTop: '3%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    alignSelf: 'center',
    borderRadius: 10,
    borderColor: Colors.GREY,
    borderStartWidth: 1,
    borderRightWidth: 1,
    borderTopWidth: 1,
  },
  inputStyle: {
    backgroundColor: Colors.PRIMARY_WHITE,
    width: '90%',
    fontSize: 16,
    fontWeight: '400',
    lineHeight: 24,
    fontFamily: Fonts.FIGTREE,
  },
  phoneInputContainer: {
    width: '72%',
    justifyContent: 'center',
    borderWidth: 1,
    alignSelf: 'center',
    borderRadius: 10,
    borderColor: Colors.GREY,
  },
  phoneInput: {
    backgroundColor: Colors.PRIMARY_WHITE,
    width: '90%',
    fontSize: 16,
    fontWeight: '400',
    lineHeight: 24,
    fontFamily: Fonts.FIGTREE,
    marginLeft: '4%',
  },
  errTxt: {
    width: '88%',
    color: 'red',
    fontSize: 12,
    alignSelf: 'center',
    marginTop: '2%',
    marginBottom: 5,
    fontFamily: Fonts.FIGTREE,
  },
  inputStyle: {
    backgroundColor: Colors.PRIMARY_WHITE,
    width: '90%',
    fontSize: 16,
    fontWeight: '400',
    lineHeight: 24,
    fontFamily: Fonts.FIGTREE,
  },
  inputContainer: {
    width: '90%',
    marginTop: '3%',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    alignSelf: 'center',
    borderRadius: 10,
    borderColor: Colors.GREY,
  },
});
export default styles;
